# Generated by Django 6.0.3 on 2026-05-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pubdate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
